begin;

create sequence if not exists public.drjack_order_id_seq start with 1002 increment by 1;

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  product text not null,
  variant text not null,
  color text not null,
  size integer not null check (size between 30 and 50),
  quantity integer not null default 0 check (quantity >= 0),
  unit_price numeric(10,2) not null check (unit_price >= 0),
  sku text,
  source_date date,
  updated_at timestamptz not null default now(),
  unique (product, variant, color, size)
);

create table if not exists public.orders (
  order_id bigint primary key default nextval('public.drjack_order_id_seq'),
  idempotency_key text not null unique,
  conversation_id text not null,
  product text not null,
  variant text not null,
  color text not null,
  size integer not null,
  quantity integer not null check (quantity between 1 and 10),
  unit_price numeric(10,2) not null,
  shipping numeric(10,2) not null default 2.00,
  total numeric(10,2) generated always as ((unit_price * quantity) + shipping) stored,
  first_name text not null,
  last_name text not null,
  phone text not null,
  street_address text not null,
  city text not null,
  status text not null default 'pending_email' check (status in ('pending_email','confirmed','email_failed')),
  email_id text unique,
  email_error text,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz
);

alter table public.inventory enable row level security;
alter table public.orders enable row level security;
revoke all on public.inventory, public.orders from anon, authenticated;
revoke all on sequence public.drjack_order_id_seq from anon, authenticated;

create or replace function public.check_stock(p_product text, p_variant text, p_color text, p_size integer)
returns jsonb language plpgsql security invoker set search_path = public as $$
declare
  item public.inventory%rowtype;
  alternatives jsonb;
begin
  select * into item from public.inventory
   where product=p_product and variant=p_variant and color=p_color and size=p_size;

  select coalesce(jsonb_agg(a), '[]'::jsonb) into alternatives from (
    select product, variant, color, size, unit_price as price
      from public.inventory
     where product=p_product and variant=p_variant and size=p_size
       and quantity > 0 and color <> p_color
     order by color limit 3
  ) a;

  return jsonb_build_object(
    'product', p_product, 'variant', p_variant, 'color', p_color, 'size', p_size,
    'available', coalesce(item.quantity, 0) > 0,
    'price', item.unit_price,
    'alternatives', alternatives
  );
end $$;

create or replace function public.reserve_order(p_order jsonb)
returns jsonb language plpgsql security invoker set search_path = public as $$
declare
  existing public.orders%rowtype;
  item public.inventory%rowtype;
  created public.orders%rowtype;
  fingerprint text;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_order->>'idempotency_key', 0));
  select * into existing from public.orders where idempotency_key=p_order->>'idempotency_key';
  if found then
    fingerprint := concat_ws('|', existing.conversation_id, existing.product, existing.variant, existing.color,
      existing.size, existing.quantity, existing.first_name, existing.last_name, existing.phone,
      existing.street_address, existing.city);
    if fingerprint <> concat_ws('|', p_order->>'conversation_id', p_order->>'product', p_order->>'variant',
      p_order->>'color', p_order->>'size', p_order->>'quantity', p_order->>'first_name',
      p_order->>'last_name', p_order->>'phone', p_order->>'street_address', p_order->>'city') then
      raise exception using errcode='P0001', message='IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_ORDER';
    end if;
    return to_jsonb(existing);
  end if;

  select * into item from public.inventory
   where product=p_order->>'product' and variant=p_order->>'variant' and color=p_order->>'color'
     and size=(p_order->>'size')::integer for update;
  if not found or item.quantity < (p_order->>'quantity')::integer then
    raise exception using errcode='P0001', message='OUT_OF_STOCK';
  end if;

  update public.inventory set quantity=quantity-(p_order->>'quantity')::integer, updated_at=now()
   where id=item.id;
  insert into public.orders(idempotency_key,conversation_id,product,variant,color,size,quantity,unit_price,
    first_name,last_name,phone,street_address,city)
  values (p_order->>'idempotency_key',p_order->>'conversation_id',item.product,item.variant,item.color,item.size,
    (p_order->>'quantity')::integer,item.unit_price,p_order->>'first_name',p_order->>'last_name',p_order->>'phone',
    p_order->>'street_address',p_order->>'city') returning * into created;
  return to_jsonb(created);
end $$;

create or replace function public.mark_email_sent(p_order_id bigint, p_email_id text)
returns jsonb language plpgsql security invoker set search_path=public as $$
declare result public.orders%rowtype;
begin
  update public.orders set email_id=coalesce(email_id,p_email_id)
   where order_id=p_order_id and status='pending_email' returning * into result;
  if not found then select * into result from public.orders where order_id=p_order_id; end if;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;
  return to_jsonb(result);
end $$;

create or replace function public.mark_email_delivered(p_email_id text)
returns jsonb language plpgsql security invoker set search_path=public as $$
declare result public.orders%rowtype;
begin
  update public.orders set status='confirmed', confirmed_at=coalesce(confirmed_at,now()), email_error=null
   where email_id=p_email_id and status <> 'confirmed' returning * into result;
  if not found then select * into result from public.orders where email_id=p_email_id; end if;
  return coalesce(to_jsonb(result), jsonb_build_object('ignored',true));
end $$;

create or replace function public.mark_email_failed(p_email_id text, p_error text)
returns jsonb language plpgsql security invoker set search_path=public as $$
declare result public.orders%rowtype;
begin
  update public.orders set status='email_failed', email_error=left(p_error,1000)
   where email_id=p_email_id and status <> 'confirmed' returning * into result;
  return coalesce(to_jsonb(result), jsonb_build_object('ignored',true));
end $$;

create or replace function public.get_order_status(p_order_id bigint)
returns jsonb language sql security invoker set search_path=public as $$
  select coalesce((select jsonb_build_object('order_id',order_id,'status',status,'email_id',email_id)
    from public.orders where order_id=p_order_id), jsonb_build_object('status','not_found'));
$$;

create or replace function public.upsert_stock_bulk(p_items jsonb)
returns jsonb language plpgsql security invoker set search_path=public as $$
declare count_rows integer;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 1000 then
    raise exception 'INVALID_STOCK_BATCH';
  end if;
  insert into public.inventory(product,variant,color,size,quantity,unit_price,sku,source_date,updated_at)
  select x.product,x.variant,x.color,x.size,x.quantity,x.unit_price,x.sku,x.source_date,now()
  from jsonb_to_recordset(p_items) as x(product text,variant text,color text,size integer,quantity integer,
    unit_price numeric,sku text,source_date date)
  on conflict (product,variant,color,size) do update set quantity=excluded.quantity,
    unit_price=excluded.unit_price,sku=excluded.sku,source_date=excluded.source_date,updated_at=now();
  get diagnostics count_rows = row_count;
  return jsonb_build_object('updated',count_rows);
end $$;

revoke all on function public.check_stock(text,text,text,integer) from public;
revoke all on function public.reserve_order(jsonb) from public;
revoke all on function public.mark_email_sent(bigint,text) from public;
revoke all on function public.mark_email_delivered(text) from public;
revoke all on function public.mark_email_failed(text,text) from public;
revoke all on function public.get_order_status(bigint) from public;
revoke all on function public.upsert_stock_bulk(jsonb) from public;
grant execute on function public.check_stock(text,text,text,integer) to service_role;
grant execute on function public.reserve_order(jsonb) to service_role;
grant execute on function public.mark_email_sent(bigint,text) to service_role;
grant execute on function public.mark_email_delivered(text) to service_role;
grant execute on function public.mark_email_failed(text,text) to service_role;
grant execute on function public.get_order_status(bigint) to service_role;
grant execute on function public.upsert_stock_bulk(jsonb) to service_role;

commit;
